spring.datasource.url=jdbc:postgresql://${NEON_HOST}/${NEON_DB}?sslmode=require
spring.datasource.username=${NEON_USER}
spring.datasource.password=${NEON_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false